### ISSUE TITLE
Any annoucement on FreeCAD forums?

### ISSUE THREAD

**Issue by luzpaz** [uribench/SheetProperties#1]
Is there an open forum thread about this? (aka does the community know about this?)

**Comment by uribench** [comment]
Hi [luzpaz](https://github.com/luzpaz). Thank you for your comment. I have posted briefly about it more than a month ago, apparently on a [thread ](https://forum.freecadweb.org/viewtopic.php?f=22&t=18437&start=20#p213232)that is not very active anymore. If there is an interest, I can elaborate on it. Considering some of the past discussions on the mentioned thread, I believe there are many parts in that code that could be of a good educational source for people.
I will close this issue, but feel free to reopen if you want.
- Thanks. Uri.
